<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Party\Module'                        => __DIR__ . '/Module.php',
    'Party\Controller\PartyController' => __DIR__ . '/src/Party/Controller/PartyController.php',
    'PartyTest\Framework\TestCase'        => __DIR__ . '/tests/Party/Framework/TestCase.php',
    'PartyTest\SampleTest'                => __DIR__ . '/tests/Party/SampleTest.php',
);
