<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('user_name'));
echo $this->formRow($form->get('user_phone'));
echo $this->formSubmit($form->get('user_call'));
echo $this->formSubmit($form->get('submit'));
//echo $this->formCollection($form);
echo $this->form()->closeTag();
